### ISSUE TITLE
How do you execute this code?

### ISSUE THREAD

**Issue by momo-AUX1** [florian-lefebvre/nuxt-app-example#1]
Do I put it in a sample html file with reference to vue.js or should I ONLY run it using the vue.js framework?

**Comment by florian-lefebvre** [comment]
You need a package manager (I recommend using pnpm). So here are the steps:
1. Clone the repo
2. Run `pnpm install`
3. Run `pnpm dev`
4. Play around

Tell me if you need more informations

**Comment by momo-AUX1** [comment]
Thank you I'll do it once I'm back home
